RSDK-13153 - Pointcloud vision service (#1)
* name change

* Makefile and stuff

* add open3d

* add sampling options

* add linter and lint

* Update from viam-labs to viam

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,11 +1,26 @@
 # see https://github.com/viamrobotics/build-action for help
 on:
   release:
-    types:
-      - released
+    types: [published]
 
 jobs:
+  validate-tag:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate tag format
+        run: |
+          TAG="${{ github.event.release.tag_name }}"
+          echo "Validating tag: $TAG"
+          if [[ $TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]*)?$ ]]; then
+            echo "Tag matches semver."
+          else
+            echo "Error: tag does not match semvar"
+            exit 1
+          fi
+
   publish:
+    needs: validate-tag
+    name: Build and Upload module
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v6
